model_name: large-v3-turbo
quantization_type: float16
device_type: cuda
task_mode: transcribe
show_clipboard_window: false
supported_quantizations:
  cpu:
  - float32
  cuda:
  - float16
  - bfloat16
  - float32
curate_transcription: true
clipboard_append_mode: false
models_directory: E:\FWTranscriber_models
